import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { readFile } from "node:fs/promises";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const codexSdkImportMetaShim = {
	name: "codex-sdk-import-meta-shim",
	setup(build) {
		build.onLoad({ filter: /[\\/]@openai[\\/]codex-sdk[\\/]dist[\\/]index\.js$/ }, async (args) => {
			const source = await readFile(args.path, "utf8");
			return {
				contents: source.replace("createRequire(import.meta.url)", "createRequire(__filename)"),
				loader: "js"
			};
		});
	}
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [codexSdkImportMetaShim],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
